version: '3'

services:
    # php
    php:
        build:
            context: ./config/docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: ${PROJECT_NAME}_php
        expose:
            - '9000'
        volumes:
            - .:/var/www/html
            - ./var/log/php:/var/log
    # nginx
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}
        ports:
            - ${WEBSERVER_PORT}:80
        depends_on:
            - php
            - db
            - elasticsearch
        volumes:
            - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
            - ./var/log/nginx:/var/log/nginx
        environment:
            - DOMAIN_NAME=${VIRTUAL_LOCALHOST}
            - VIRTUAL_HOST=${VIRTUAL_HOST}

    db:
        image: mysql:5.7
        container_name: ${PROJECT_NAME}_db
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./var/db-data:/var/lib/mysql
        command: mysqld --socket="/tmp/mysql.sock" --bind-address=0.0.0.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - DOMAIN_NAME=db.${VIRTUAL_LOCALHOST}

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        container_name: ${PROJECT_NAME}_es
        volumes:
            - ./var/es-data:/usr/share/elasticsearch/data
        environment:
            - cluster.name=${PROJECT_NAME}
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - DOMAIN_NAME=es.${VIRTUAL_LOCALHOST}
        ulimits:
            memlock:
                soft: -1
                hard: -1

    # ---------#
    #  TOOLS   #
    # ---------#

    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        container_name: ${PROJECT_NAME}_kibana
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - DOMAIN_NAME=kibana.${VIRTUAL_LOCALHOST}

networks:
    default:
        external:
            name: ${PROJECT_NAME}